# {'Compose file format': 3.7, 'Docker Engine release': 18.06.0*} (0x0)
version: '3.7'

# Services collectively make up a distributed application. (0x1)
services:

  # Test.
  asset_server:
    build:
      context: .
      dockerfile: ./applications/asset_server/Dockerfile
    environment:
      _SERVICE_NAME: "asset_server"
    tty: true
    ports:
      - "80:80"
    volumes:
      - nexus_volume:/v
      - ./:/quasar_source

  postgres_server:
    image: postgres
    tty: true
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - /Users/utarsuno/git_repos/quasar_source/generated_output/postgres:/var/lib/postgresql/data

volumes:
  nexus_volume:
    external: true
  postgres_data:

