# The version of the Docker compose file format to use.
version: '3.7'

# TODO: Investigate into 'container_name', it breaks builds.

services:

  # Serves static content and forwards requests to servers.
  nginx:
    #hostname: nginx
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    environment:
      _SERVICE_NAME: "nginx"
    #container_name: nginx
    tty: true
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - nexus_volume:/v

  # Manages automated jobs, builds, etc.
  jenkins:
    #hostname: jenkins
    build:
      context: .
      dockerfile: ./applications/jenkins/Dockerfile
    environment:
      _SERVICE_NAME: "jenkins"
      JAVA_OPTS: "-Xmx3072m" # 3GB memory.
      JENKINS_OPTS: "--logfile=/var/log/jenkins/jenkins.log"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home

  # RabbitMQ broker.
  rabbit_manager:
    #hostname: rabbit_manager
    build:
      context: .
      dockerfile: ./applications/rabbitmq_manager/Dockerfile
    environment:
      _SERVICE_NAME: "rabbit_manager"
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit_manager
    tty: true
    #container_name: rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"

  # MySQL server, no custom logic attached, just the stand-alone server.
  mysql_server:
    hostname: mysql_server
    build:
      context: .
      dockerfile: ./applications/mysql_server/Dockerfile
    environment:
      _SERVICE_NAME: "mysql_server"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      PYTHONPATH: "/quasar_source"
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: "nexus_courier"
    #image: mysql
    #container_name: mysql_server
    #command: mysqld --user=root --verbose
    tty: true
    depends_on:
      - rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
    #  - ./applications/mysql_server/dbcreation.sql:/tmp/dbcreation.sql
    #  - ./applications/mysql_server/import.sh:/tmp/import.sh
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: nexus_network

volumes:
  nexus_volume:
    external: true
  jenkins-log:
    external: true
  jenkins-data:
    external: true

