# {'Compose file format': 3.7, 'Docker Engine release': 18.06.0*} (0x0)
version: '3.7'

# Services collectively make up a distributed application. (0x1)
services:

  # Serves static content and forwards requests to servers.
  nginx:
    #hostname: nginx
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    environment:
      _SERVICE_NAME: "nginx"
    #container_name: nginx
    tty: true
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - nexus_volume:/v
    depends_on:
      - nexus_courier

  # RabbitMQ broker.
  rabbit_manager:
    #hostname: rabbit_manager
    build:
      context: .
      dockerfile: ./applications/rabbitmq_manager/Dockerfile
    environment:
      _SERVICE_NAME: "rabbit_manager"
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit_manager
    tty: true
    #container_name: rabbit_manager
    volumes:
      - './applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config'
      - './applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json'
    ports:
      - '5672:5672'
      - "15672:15672"
      - "25672:25672"

  rabbit2:
    hostname: rabbit2
    build:
      context: .
      dockerfile: ./applications/nexus_server/Dockerfile
    environment:
      SERVICE_NAME: "rabbit2"
      PYTHONPATH: ":/quasar_source"
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    tty: true
    #container_name: rabbit2
    depends_on:
      - rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./applications/nexus_server:/quasar_source/applications/nexus_server
      - ./libraries:/quasar_source/libraries
      - ./scripts:/quasar_source/scripts
      - nexus_volume:/v

  nexus_courier:
    hostname: nexus_courier
    build:
      context: .
      dockerfile: ./applications/nexus_courier/Dockerfile
    environment:
      _SERVICE_NAME: "nexus_courier"
      #
      PYTHONPATH: ":/quasar_source"
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: "nexus_courier"
      #
      NC_ARG_RABBIT_HOST: "amqp://guest:guest@rabbit_manager/"
      NC_ARG_RABBIT_QUEUE: "queue_nexus_courier"
      NC_ARG_DEBUG_ON: "true"
      NC_ARG_WEBSOCKET_PORT: "3001"
    #container_name: nexus_courier
    tty: true
    depends_on:
      - rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./applications/nexus_courier:/quasar_source/applications/nexus_courier
      - ./libraries:/quasar_source/libraries
      - ./scripts:/quasar_source/scripts
      - ./generated_output/nexus_courier:/quasar_source/generated_output/nexus_courier

networks:
  default:
    external:
      name: nexus_network

volumes:
  nexus_volume:
    external: true
