# The version of the Docker compose file format to use.
version: '3.7'

# TODO: Investigate into 'container_name', it breaks builds.

services:

  # Serves static content and forwards requests to servers.
  nginx:
    #container_name: nginx
    build:
      context: .
      dockerfile: ./applications/nginx/Dockerfile
    tty: true
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - nexus_volume:/v
    depends_on:
      - nexus_courier

  # RabbitMQ broker.
  rabbit_manager:
    #container_name: rabbit_manager
    build:
      context: .
      dockerfile: ./applications/rabbitmq_manager/Dockerfile
    tty: true
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"

  rabbit2:
    #container_name: rabbit2
    build:
      context: .
      dockerfile: ./applications/nexus_server/Dockerfile
    tty: true
    hostname: rabbit2
    depends_on:
      - rabbit_manager
    environment:
      - PYTHONPATH=:/quasar_source
      - RABBITMQ_ERLANG_COOKIE="secret string"
      - RABBITMQ_NODENAME=rabbit2
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./applications/nexus_server:/quasar_source/applications/nexus_server
      - ./libraries:/quasar_source/libraries
      - ./scripts:/quasar_source/scripts
      - nexus_volume:/v

  nexus_courier:
    #container_name: nexus_courier
    build:
      context: .
      dockerfile: ./applications/nexus_courier/Dockerfile
    environment:
      - PYTHONPATH=:/quasar_source
      - RABBITMQ_ERLANG_COOKIE="secret string"
      - RABBITMQ_NODENAME=nexus_courier
    tty: true
    hostname: nexus_courier
    depends_on:
      - rabbit_manager
    volumes:
      - "./applications/rabbitmq_manager/rabbitmq.config:/etc/rabbitmq/rabitmq.config"
      - "./applications/rabbitmq_manager/definitions.json:/etc/rabbitmq/definitions.json"
      - ./applications/nexus_courier:/quasar_source/applications/nexus_courier
      - ./libraries:/quasar_source/libraries
      - ./scripts:/quasar_source/scripts
      - ./generated_output/nexus_courier:/quasar_source/generated_output/nexus_courier

networks:
  default:
    external:
      name: nexus_network

volumes:
  nexus_volume:
    external: true
