# {'Compose file format': 3.7, 'Docker Engine release': 18.06.0*} (0x0)
version: '3.7'

# Services collectively make up a distributed application. (0x1)
services:

  # Test.
  asset_server:
    build:
      context: '.'
      dockerfile: './applications/asset_server/Dockerfile'
    ports:
      - '80:80'
    volumes:
      - 'nexus_volume:/v'
      - './:/quasar_source'
    environment:
      _SERVICE_NAME: 'asset_server'
      DATABASE_URL: 'pgsql://postgres:password@postgres_server:5432/postgres'
      SYMFONY_ENV: 'dev'
      RUN_CONSOLE: 'php /quasar_source/libraries/php/console.php'
      RUN_DEPLOYER: './dep --file=/quasar_source/libraries/php/deploy.php'
      FLAG_INPUT: '--file_input'
      FLAG_OUTPUT: '--file_output'
      CMD_CONSOLE_MINIFY: 'minify:css'
      CMD_CONSOLE_GZIP: 'file:gzip'
      CMD_DEPLOYER_RUN_ALL_TESTS: 'run_all_tests -vvv'
      CMD_DEPLOYER_FULL_BUILD: 'full_build -vvv'
      CMD_DEPLOYER_DEBUG: 'debug -vvv'
      CMD_DEPLOYER_BUILD_NEXUS_COURIER: 'build_nexus_courier -vvv'
    tty: true

  postgres_server:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - '/Users/utarsuno/code/quasar_source/var/db/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'password'
    tty: true

volumes:
  nexus_volume:
    external: true
  postgres_data:
    external: true
