# {'Compose file format': 3.7, 'Docker Engine release': 18.06.0*} (0x0)
version: '3.7'

# Services collectively make up a distributed application. (0x1)
services:

  asset_server:
    tty           : true
    container_name: asset_server
    #network_mode  : host # Temp solution for connecting to the LAN FTP server
    build         :
      context   : '.'
      dockerfile: './applications/asset_server/Dockerfile'
    ports         :
      - '80:80'
      - '21:21'
      - '20:20'
      - '40000-50000:40000-50000'
    volumes       :
      - 'nexus_volume:/v'
      - './:/quasar_source'
    environment   :
      _SERVICE_NAME: 'asset_server'
      DATABASE_URL : 'pgsql://postgres:password@postgres_server:5432/postgres'

  postgres_server:
    tty           : true
    container_name: postgres_server
    image         : postgres
    ports         :
      - '5432:5432'
    volumes       :
      - '/Users/utarsuno/code/quasar_source/var/db/postgres:/var/lib/postgresql/data'
    environment   :
      POSTGRES_USER    : 'postgres'
      POSTGRES_DB      : 'postgres'
      POSTGRES_PASSWORD: 'password'

#networks:
#  default:
#    external:
#      name: nexus_network

volumes:
  nexus_volume:
    external: true
  postgres_data:
    external: true
#  jenkins-log:
#    external: true
#  jenkins-data:
#    external: true

  # Serves static content and forwards requests to servers.
#  dapp_nginx:
    #hostname: nginx
#    build:
#      context: .
#      dockerfile: ./applications/nginx/Dockerfile
#    environment:
#      _SERVICE_NAME: "dapp_nginx"
    #container_name: nginx
#    ports:
#      - "80:80"
#      - "3000:3000"
#    tty: true
#    volumes:
#      - nexus_volume:/v
#      - ./applications/nginx/nginx.nginx:/etc/nginx/nginx.conf

  # Manages automated jobs, builds, etc.
#  jenkins:
    #hostname: jenkins
#    build:
#      context: .
#      dockerfile: ./applications/jenkins/Dockerfile
#    environment:
#      _SERVICE_NAME: "jenkins"
#      JAVA_OPTS: "-Xmx3072m" # 3GB memory.
#      JENKINS_OPTS: "--logfile=/var/log/jenkins/jenkins.log"
#    tty: true
#    volumes:
#      - jenkins-log:/var/log/jenkins
#      - jenkins-data:/var/jenkins_home


