# The version of the Docker compose file format to use.
version: '3.7'

services:

  # Builds projects and maintains developer's local environment.
  code_manager:
    container_name: code_manager
    build:
      context: .
      dockerfile: ./applications/code_manager/Dockerfile
    environment:
      - PYTHONPATH=:/quasar_source
      - CODE_BUILDER_PATH_DB=/quasar_source/generated_output/local/code_manager/db.sqlite
      - CODE_BUILDER_PATH_OUTPUT=/quasar_source/generated_output/web_assets/
      - CODE_BUILDER_PATH_VOLUME=/v/
      - LD_LIBRARY_PATH=/usr/lib/libamqpcpp.so.3.1
    tty: true
    volumes:
      - ./:/quasar_source
      - nexus_volume:/v

networks:
  default:
    external:
      name: nexus_network

volumes:
  nexus_volume:
    external: true
