#index:
#    path: /
#    controller: App\Controller\DefaultController::index

qa_test:
  path: /qa_test
  controller: CodeManager\Controller\QAController::test_response

run_unit_tests:
  path: /run_unit_tests
  controller: CodeManager\Controller\QAController::run_unit_tests

