services:
    _defaults:
        autowire: true
        autoconfigure: true

    CodeManager\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    CodeManager\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
