parameters:
    env(DATABASE_URL): 'pgsql://postgres:password@postgres_server:5432/postgres'

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        charset: utf8
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            CodeManager:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'CodeManager\Entity'
                alias: CodeManager
