<?php declare(strict_types=1);

namespace CodeManager\Repository\CodeManager;

use CodeManager\Entity\Abstractions\EntityInterface;
use CodeManager\Entity\CodeManager\EntityCodeBuild;
use CodeManager\Repository\Abstractions\AbstractRepository;
use CodeManager\Repository\Abstractions\QueryableRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use CodeManager\Entity\Abstractions\Traits\Enum\EntityTableNames as TABLE;
use CodeManager\Entity\Abstractions\Traits\Enum\EntityFields     as FIELD;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Mapping\Entity;
use QuasarSource\SQL\DBTable;

/**
 * Class RepoCodeBuild
 * @package CodeManager\Repository\CodeManager
 */
class RepoCodeBuild extends QueryableRepository {

    #protected $entity_class = EntityCodeBuild::class;
    public const ENTITY_CLASS = EntityCodeBuild::class;

    /**
     * @param int $build_type
     * @return EntityCodeBuild
     */
    public function get_new_code_build(int $build_type=EntityCodeBuild::BUILD_TYPE_NOT_SAFE): EntityCodeBuild {
        $entity = new EntityCodeBuild($build_type);
        return $entity;
    }

    public function save_entity($entity, bool $save_db_state = false): void {
        parent::save_entity($entity, $save_db_state); // TODO: Change the autogenerated stub
    }

    public function fetch_or_generate_last_build(): EntityCodeBuild {
        var_dump($this->get_table_size());

        exit(3);

        #var_dump($this->get_table_num_rows());

        var_dump($this->analyze_table());

        $table_rows = $this->get_table_num_rows();
        if ($table_rows === 0) {
            return new EntityCodeBuild();
        }
        var_dump('ELSE, HANDLE THIS!');
        exit(2);
    }

    public function get_datetime_of_last_successful_build(): ?DateTime {
        #$results = $this->execute_query(QueryGenerator::get_db_size('postgres', false), true);
        #var_dump('Here are query results!');
        #var_dump($results);

        #var_dump($this->get_table_size());
        #var_dump($this->get_table_num_rows());
        return null;
        #var_dump($this->get_newest_entity());
        #var_dump($this->get_oldest_entity());

        #$entity = $this->get_newest_entity();
        #var_dump('The newest entity is:');
        #var_dump($entity);

        #return $entity;
    }
}



