reference_URLs:
  0x0: 'https://docs.docker.com/compose/compose-file/compose-versioning/#version-3'
  0x1: 'https://docs.docker.com/get-started/part3/'

python:
  git_abstraction: 'pip3 install gitpython'
  yaml_parser    : 'pip3 install pyyaml'
  color_print    : 'pip3 install lazyme'

development_progress_snapshots:
  - 'https://i.imgur.com/839NKO1.jpg'
  - 'https://i.imgur.com/iytE8bW.png'
  - 'https://i.imgur.com/3hxELAM.png'
  - 'https://i.imgur.com/ygTs717.png'
  - 'https://i.imgur.com/CFmXgTf.png'
  - 'https://i.imgur.com/xKp1n9a.png'
  - 'https://i.imgur.com/aShuQKw.png'
  - 'https://i.imgur.com/FYvnV5B.png'
  - 'https://i.imgur.com/V8GOzD9.png'

useful_links:
  - 'https://unicode.org/emoji/charts/full-emoji-list.html'
  - 'http://qnimate.com/measuring-web-page-performance-using-modern-javascript-apis/'
  - 'https://caylent.com/docker-commands-cheat-sheet/'

todo_links:
  - 'https://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images'
  - 'https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile'
  - 'https://gist.github.com/denji/8359866'
  - 'https://engineering.riotgames.com/news/jenkins-docker-proxies-and-compose'
  - 'https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/'

nginx_http2_links:
  - 'https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-16-04'
  - 'https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04'
  - 'https://bjornjohansen.no/optimizing-https-nginx'
  - 'https://bjornjohansen.no/redirect-to-https-with-nginx'
  - 'https://bjornjohansen.no/securing-nginx-ssl'
  - 'https://bjornjohansen.no/enable-http2-on-nginx'
  - 'https://gist.github.com/mjumbewu/7fa64e83e02d613f4daa031d66d6c247'
  - 'https://stackoverflow.com/questions/34971886/err-empty-response-with-ghost-0-7-5-nginx-1-9-https-and-http-2'
  - 'https://helpdesk.ssls.com/hc/en-us/articles/203427642-How-to-install-a-SSL-certificate-on-a-NGINX-server'
  - 'https://www.digicert.com/csr-ssl-installation/nginx-openssl.htm#create_csr_openssl'
  - 'https://www.sslshopper.com/article-most-common-openssl-commands.html'
  - 'https://www.digicert.com/csr-ssl-installation/nginx-openssl.htm#create_csr_openssl'
  - 'https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-16-04'
  - 'https://bjornjohansen.no/optimizing-https-nginx'
  - 'https://bjornjohansen.no/redirect-to-https-with-nginx'
  - 'https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https'
  - 'https://www.3cx.com/blog/docs/ssl-crt-csr/'

docker:
  commands:
    clean_up_commands:
      - 'docker system prune'
      - 'docker container prune'
      - 'docker network prune'
      - 'docker volume prune'
    total_size_used:
      - 'docker system df'
    examples:
      - 'docker-compose -f docker-compose.asset_server.yml up -d postgres_server' # 192.168.1.170

bash_commands:

procedures:
  update_ubunutu:
    - 'sudo apt update'
    - 'apt dist-upgrade'
    - 'apt-get autoremove'
    - 'apt install update-manager-core'
    - '// Restart server before next commands.'
    - 'sudo do-release-upgrade'

# C O N S T A N T S
css_ids:
  a: 'paused_background_filter'
  b: 'pause_display'
  c: 'pause_display_title'
  d: 'pause_display_sub_title'

  e: 'center_cursor'
  f: 'cursor_default'
  g: 'cursor_icon'

  h: 'no_touch'
  i: 'gui_canvas'
  j: 'outline_green'
  k: 'canvas_main'

css_ids_generated:
  l: 'gui_2D_debug_information'
  m: 'gui_2D_logs'
  n: 'gui_2D_typing'


directories:
  /v/: 'nexus_volume'
