service_bundles:
  asset_server:
    path: 'docker-compose.asset_server.yml'
    services:
      postgres_server:
      asset_server:

services:
  postgres_server:
    type      : 'db'
    secrets   : []
  asset_server:
    type      : 'php'
    secrets   : ['asset_server_db']

